id: I98499F08
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:34:00+00:00'
last_modified: '2022-06-08T08:40:48.243630+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20401
  title: དབུ་མ་ལ་འཇུག་པ་རྩ་བ་དང་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E315:
      image_group_id: I1KG10486
      title: ''
      total_pages: 488
      order: 1
      base_file: E315.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
