id: P009108
initial_creation_type: ocr
source_metadata:
  id: bdr:W20401
  title: དབུ་མ་ལ་འཇུག་པ་རྩ་བ་དང་འགྲེལ་པ།
  author: ''
  volumes:
    100e977742ab40f6aaf9af249daa9306:
      image_group_id: I1KG10486
      title: ''
      volume_number: 1
      total_pages: 488
