id: P009108
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20401
  title: དབུ་མ་ལ་འཇུག་པ་རྩ་བ་དང་འགྲེལ་པ།
  author: ''
  volumes:
    100e977742ab40f6aaf9af249daa9306:
      image_group_id: I1KG10486
      title: ''
      volume_number: 1
      total_pages: 488
      base_file: v001.txt
